### ISSUE TITLE
Equipment positions in loadouts get messed up after every save

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#383]
I usually try to position the equipment in my loadouts as such that I can see on one glance what's in the mech: First all weapons into one slot, then ammo, then heat sinks etc.

As an example, this is the order of items I have in the left torso on one mech:
SSRM4 / SSRM4 Ammo / Gauss Ammo x2 / Double Heat Sink x2

Unfortunately, this order is messed up when saving the garage. It now is:
Gauss Ammo / Double Heat Sink / SSRM4 Ammo / Double Heat Sink / SSRM4 / Gauss Ammo

This is just one example, but basically every slot in every loadout is affected by this. And not only the mech slots but the module slots as well! The in-game MechLab also had this problem previously, but fortunately PGI was able to fix it.

So if it's possible to keep equipment positions stable in future versions of LSML it would be greatly appreciated! :)

Thanks a lot!

**Comment by EmilyBjoerk** [comment]
If I remember correctly, this is due to a canonicalisation of loadouts to
be able to detect duplicates. I.e. all components are sorted according to
some interval criteria. This means that loadouts which behave identically
in the game are considered equal regardless of the order of slots in the
components.

I'm at this moment not entirely sure what will happen if I remove this
canonicalisation. But I do remember putting it in for a reason... I'll give
it a try and see what, if anything breaks. If it looks like too much work,
I'll have to postpone this to the next major release. Otherwise I can get
it into the next bug fix release.

**Comment by Zesaric** [comment]
Thanks for your swift reply and your explanation. However, what you describe does not really match what I noticed:

- If I clone a loadout, it saves items in other positions than in the initial loadout . I.e. I can have two identical mechs, but the item positions in the two loadouts are different.
- Sometimes it even happens that the position of items changes despite the fact that I haven't touched that particular loadout at all.

So right now my current impression is that LSML positions items completely at random at every save.

One idea to solve this could be to add an additional XML field (e.g. "PositionID") and assign a unique number to every slot. This number could be saved in the garage file to make sure that an item remains where the user put it.

But this just as a suggestion as obviously you're the one who can judge best how to implement features into LSML.

**Comment by EmilyBjoerk** [comment]
The issue was an unsuitable use of an priority queue without stable ordering.

**Comment by Zesaric** [comment]
Thanks for your reply and your efforts to fix this. I am absolutely impressed by how professional you handle such requests and can only say "Keep up the great work". Excellent!
