### ISSUE TITLE
problem with SSL when exporting to smurfy

### ISSUE THREAD

**Issue by soggygorilla** [EmilyBjoerk/lsml#384]
"Error: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: Unable to find valid certification path to requested target"

**Comment by EmilyBjoerk** [comment]
This is likely a temporary issue with smurfys certificate. I'll make the
error more friendly.

@smurfy any info?

**Comment by smurfy** [comment]
I recently switched the certificate to a SAN one to support more than one domain.

I tested with almost all browsers and no problems there.

It currently contain a certificate in the chain which only supports SHA1, maybe this is the issue.

**Comment by EmilyBjoerk** [comment]
Okay that means I will have to have a look at that then.

**Comment by smurfy** [comment]
Sorry to cause you problems. I googled a bit and only find that the problem occures with self-signed certificates or missing intermediate certificates.

But neither thing is the case.

I did a ssl test, which shows which certificate is the problem.

https://www.ssllabs.com/ssltest/analyze.html?d=mwo.smurfy-net.de&hideResults=on

**Comment by smurfy** [comment]
I did some future tests, the root certificate is the same as before.
Also all certs with the old chain where sha1 ones. so this should not be the problem.
My guess is, that somehow java has problems with SAN certificates.

**Comment by soggygorilla** [comment]
http://serverfault.com/questions/426634/unable-to-find-valid-certification-path-to-requested-target-while-cas-authentica

found that link that resembles the problem. im not expert on SSL certificates though

**Comment by soggygorilla** [comment]
and this one 

http://tiku.io/questions/448150/trust-all-ssl-certificates-in-java-playframework-2-2

**Comment by smurfy** [comment]
@soggygorilla thank, you, found many of this too. most of them have in common, that the problem is they are using self-signed certificates. 

But thats not the case here. Only things which are problematic with the certificate is, that:
* One of the intermediate certificates is SHA1
* The ocsp server is down.

The SHA1 thing should not be the problem only browser i know of which does not like SHA1 certs is chrome, which will accept them until 2017 tho.

The ocsp server beeing down also should not cause any problems. I disabled OCSP check in my java settings, but still getting the error.

Only possible error i found, is a java bug (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6668231)  but this should be fixed and i use a recent java build.

**Comment by smurfy** [comment]
Ok, it's not a problem with SAN (the error is different if it does not find the name in the certificate)

Switched to SNI and the original certificate. Problem is, it will run-out 2015-03-10 :( 

Maybe you will find out what the problem with the new cert is.
You can use: https://freessl.wosign.com/en/freessl.html or https://www.checkmyping.com/  to test with.

**Comment by EmilyBjoerk** [comment]
I have not had time to check yet but I think it might be as simple as I
just have to update the public signature of your certificate that I bundle.
As you are using a self signed certificate I had to make a key store to
allow java to accept it.

**Comment by aweFalafelApps** [comment]
I don't know how helpful it will be, but I did finally get a report today and after testing the exception I'm getting is the following:

javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

Nothing in my code has changed. Let me know if there is anything else I can provide.

**Comment by smurfy** [comment]
Strange, currently i still run the old certificate again as SNI, with the new one as main.
Both certificates are valid certificates and trusted by all browsers. (and not self-signed)

But i want to switch to the new certificate soon, because the old one runs out in 20 days.

@EmilyBjoerk tell me if you have time to test and i will switch my cert again.

**Comment by EmilyBjoerk** [comment]
@smurfy  I have time to work on this today. Could you please switch over and let me know?

**Comment by smurfy** [comment]
using the new cert now

**Comment by EmilyBjoerk** [comment]
Is this certificate self-signed? Can you give the the public cert for the root CA?

**Comment by EmilyBjoerk** [comment]
Okay I think I managed to trust the root CA of Wo Sign. If you decide to use another certificate issuer in the future, please let me know ahead of time. Unless it's a major issuer, I need to add it to the list of trusted issuers in the keystore file in LSML.

**Comment by soggygorilla** [comment]
Same issue is back again :(

**Comment by smurfy** [comment]
@soggygorilla Update to 1.6.5

**Comment by soggygorilla** [comment]
yay it works, thank you
