### ISSUE TITLE
Selective ghost heat

### ISSUE THREAD

**Issue by trlababalan** [EmilyBjoerk/lsml#386]
Edited: This "issue" was previously called "More UI interaction and selective ghost heat". I've edited this into three separate ones for planning purposes. 

I would like to see how much sustained DPS my build makes with ghost heat included. Take for example 4xSRM4 on a JR7-O or 4xAC/2 King Crab. (Another edit: AC2 has no more ghost heat.)

**Comment by EmilyBjoerk** [comment]
Taking ghost heat into account has been requested previously. It is a bit tricky as the resulting sustained DPS depends heavily on the firing pattern.

Consider a 6x SRM4 Mad Dog, the sustained DPS (including ghost heat) is very different if you fire 3+3, 4+2, 5+1 or alpha strike (but they have the same Max DPS). To be able to calculate the correct sustained DPS the user needs to specify a firing pattern which complicates things very much.

Assuming that the user always alpha strikes isn't really ideal either as the above Mad Dog with 6x SRM4 can also comfortably carry 3x ER LLAS with max armor. Now, a sustained DPS using alpha strikes with this loadout will not make any sense and the numbers will be useless and confusing.

I'm trying to come up with a solution using the new WeaponLab feature in 1.7.0 but I'll have to see how it turns out.

**Comment by trlababalan** [comment]
Considering a 6x SRM4 Mad Dog; 3+3 does no ghost heat. firing 4+2 would make use of #389 and maybe #388 for excluding those 2 SRMs from ghost heat calculations. 
Sustained DPS (with ghost heat) would be calculated with the ghost heat of 4 SRMs.

Users would be able to see which weapons can they fire in bigger alphas with little change to heat and DPS. Some would search for the highest possible alpha with reaching 100% heat. (My guess ER/PPC and AC20 builds).

**Comment by EmilyBjoerk** [comment]
This issue will be implemented by #275.
