### ISSUE TITLE
Leave armor unchanged when using "Loadout>Strip Mech"

### ISSUE THREAD

**Issue by Zesaric** [EmilyBjoerk/lsml#391]
I use the "Strip Mech" function quite frequently to try new loadouts. Unfortunately, this also resets the armor values - which is a bit of a pain, as the armor has to be set manually over and over again.

So basically resetting the armor values should not be linked to "Strip Mech", because there is the separate option "Armor>Strip Armor" to do this.

If this change could be implemented, it would be greatly appreciated! :-)

**Comment by EmilyBjoerk** [comment]
If you use the automatic armor distribution feature you won't have this issue as the amount set on the slider will not be reset by strip mech. The feature will save you the trouble of manually setting the armor as well.

**Comment by Zesaric** [comment]
Thanks for the tip, but it is very often that I assign armor manually in order to optimize asymmetric loadouts. So unfortunately the automatic armor distribution feature is not an option for me.

Don't you see any chance of stripping armor separately from the equipment? Or perhaps apply the MWO GUI style where you can choose what to strip (Items/Modules/Armor)?

**Comment by EmilyBjoerk** [comment]
It is possible to do and it's not that difficult. However, at the moment I only have time to do the bare minimum to maintain the software (bugfixes). I hope to get time to work on LSML again at a future date but life has been kicking my ass the past 6 months or so (and there is no end in sight). :/ 

So while I can do it I probably won't get around to it for a while, which is why I tried to offer an alternative workflow with AAD. I'm quite confused by your last statement regarding AAD, it works equally well for all loadout types (asymmetric or not). Just set the total amount of armor points and adjust those that are wrong (the rest will re-adjust and you will arrive at your optimal distribution without adjusting all of the locations).

**Comment by Zesaric** [comment]
I fully understand about your limited time and am grateful that you are trying to help nevertheless. I tried the AAD feature and obviously it does what you say. However it has two main problems:

- Even if I set the slider to max, the armor is not maxed.
- Even if AAD is active, using "Loadout>Strip mech" will reset the values to zero (which was my original problem)

It's not that big of a problem of course - I just wanted to suggest an improvement and give feedback that AAD (while otherwise being a cool feature) is not the remedy for the mentioned issue.

**Comment by EmilyBjoerk** [comment]
Regarding your two points there. The first one is by design. It will go to
the closest full half-ton to max armor to allow you maximal use of your
tonnage. If there is more points of armour than that not being applied,
then that is a bug.

If you really want max armor everywhere in the final loadout (most people
don't), then there is the max armor feature which will override AAD.

The second point is a bug. If you add something to the loadout after it has
been stripped, the armor amount on the slider will be applied to the
loadout. So if you just ignore the fact that it shows zero armor after
stripping and go on building the loadout "it should just work".

The wiki page has some documentation on the feature. I hope this helps. AAD
is possibly the least known feature but it is one of the most useful and
timesaving features.

**Comment by Zesaric** [comment]
Thanks for your quick reply. I understand the reasoning behind the full/half-ton and agree this makes sense. What I mostly do is to use the max armor feature, then equip the items I want and in the end reduce armor as required in order to fit all of them. Which I guess is something I could do with AAD as well - maybe even quicker.

However, what I also do is to use LSML as an *exact* representation and documentation of the loadouts I have in game. I also analyze the resulting XML file via Excel e.g. to quickly find engines, modules, etc. - or irregularities between mechs that I feel should have identical armor distribution.

This is why I set exact armor values manually, and this is why I cannot use strip mech or AAD in their current form. Hope that explains my request? In any case thanks a bunch for all the time you spend taking care of the software and your users.
