### ISSUE TITLE
Unable to startup IPC - Error:java.net.BindException: Address already in use: JVM_Bind

### ISSUE THREAD

**Issue by 12DG-Ghostbear** [EmilyBjoerk/lsml#394]
LSML version: 1.6.5

Steps to reproduce:
1. Upon opening LSML I directly receive
Unable to startup IPC. Links with builds (lsml://...) will not work.
Error:java.net.BindException: Address already in use: JVM_Bind

![lsml](https://cloud.githubusercontent.com/assets/12081271/7293416/2d0b6be6-e9a5-11e4-8f59-1c6bdae2702d.jpg)
![lsml2](https://cloud.githubusercontent.com/assets/12081271/7293654/152b145c-e9a7-11e4-993b-2d3e43200722.jpg)

**Comment by 12DG-Ghostbear** [comment]
I uninstalled all previous releases and reinstalled 1.6.5 changed nothing.
If you require anything specific just tell me.

**Comment by LiSongMWO** [comment]
This commonly happens when you have multiple instances of lsml running
simultaneously. Or some other program is listening to/or preventing access
the the required port. Typically a firewall.

To make links open in your current lsml window (instead of a new one for
each loadout) lsml needs to talk with itself over local sockets.

If you want this function, you need to allow lsml to listen to
127.0.0.1:63782 in your firewall (this is completely safe and well not send
our receive data to the Internet) or simply allow it the first time your
firewall asks you what to do.

If you don't trust lsml you can just ignore the message, lsml will function
correctly regardless. But clicking on lsml links in your browser etc will
not work, you can still manually import the links by copy pasting them into
lsml's import link dialog.

**Comment by 12DG-Ghostbear** [comment]
Hello Li Song,

thanks for your reply.
I have only on LSML Instance open each time.

I created said FW Rule and it did not change the behavior.
Also I fully disabled the FW for a Minute to test and the error remained the same.

May it make sense to downgrade the JRE to a 1.7.X release for LSML?

Greetings Bastian

**Comment by LiSongMWO** [comment]
The error message says that the address is already in use. It may be that
some other program you are using has already claimed the address
(unlucky...).

You can try closing all other programs and see if it helps. Alternatively
you can try to boot into safe mode and see if the error disappears. If it
does then it's something on your computer that is using the port.

You can try with java 7 but I doubt it will have an effect. There are many
users with java 8 and no problems. And the error message is pretty clear...
I have a hard time believing that it would be a jvm bug.

I'm sorry to say but right now it seems to be something with your computer.

**Comment by 12DG-Ghostbear** [comment]
Is there a way to change the port accessed on local host to something different then 63782?

**Comment by LiSongMWO** [comment]
At the moment unfortunately, no. I will make it a user preference in the
configuration file. And make it automatically try another port of it fails
once.

Once I get some time to work on lsml again.

**Comment by 12DG-Ghostbear** [comment]
Thank you very much for that!

**Comment by EmilyBjoerk** [comment]
If LSML is unable to bind the port, the user will be prompted to either random select a new port (should work most of the time) or to manually enter a new port or the disable the functionality. If LSML is able to bind a port it will just quietly go about it's business.
