### ISSUE TITLE
Laser duration is rounded up?

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#443]
I noticed that in the ingame mechlab, the laser duration is listed with two decimal places, like the clan SPL has a duration of 0.75. The program seems to round this up to 0.8?

**Comment by EmilyBjoerk** [comment]
It's only rounded for display, there is simply too little space to show the full precision.

The values used for calculation are accurate.

**Comment by Question2** [comment]
Isnt there very little space difference between 1 and 2 decimal points?

**Comment by EmilyBjoerk** [comment]
Yes the space difference is small, but the amount of space available is also small because LSML has to function at resolutions as low as 1024x768. 

The following would get much too cluttered if there was an additional decimal of accuracy on damage, burn and dps row for example. If you want to see more decimals you can look in the weapons tab.
![image](https://cloud.githubusercontent.com/assets/5306929/11571336/188c531c-99fc-11e5-88e1-5dee64dc494a.png)

**Comment by EmilyBjoerk** [comment]
At any rate, I agree I would like more decimal points but I just feel that the sacrifice of readability isn't worth it for smaller screens. It will work differently in the new UI so it'll be fixed there.

**Comment by Question2** [comment]
Why not make it so that the program will only display decimal values if it is higher than 0?

E.G. In your screenshot itw ould just display Damage : 9, while it would display ROF : 4.5.

**Comment by EmilyBjoerk** [comment]
Because the problem will still exist when it can't do that because not
enough numbers are even.

At any rate I'm not putting effort into polishing the old ui as I about to
throw it away in 2.0.

**Comment by EmilyBjoerk** [comment]
The improvements will be implemented by #446. I'm closing this for now.
