### ISSUE TITLE
Problem Importing a Shadow Cat build from my saved Smurfy MechLab

### ISSUE THREAD

**Issue by EricStork** [EmilyBjoerk/lsml#481]
LSML version: 1.7.2

Link to problem build:
http://mwo.smurfy-net.de/mechlab#i=296&l=180645f04ff358e4ddbdc3500c3cbaff3d599e9b

Steps to reproduce:
1. open lsml
2. choose Garage > Import from Smurfy
3. add correct API-key then click Import
4. causes screenshot named Li Song Smurfy Import Error.jpg seen below

Actual result: Everything except the SHC-PRIME imports from my old Smurfy MechLab.

Expected result: Everything imports from my old Smufy MechLab.

When Importing from Smurfy MechLab saved builds, I get the error shown in the screenshot. The Shadow Cat-Prime build said to cause a problem is using the same A-pod Left Arm as 2 other builds that import fine. Every build I had imported except the one at the link above.

Screenshot of error received:
https://rogue1618.files.wordpress.com/2016/02/li-song-smufy-import-error.jpg

**Comment by EmilyBjoerk** [comment]
I have debugged this and found two issues here. The first is that the link generated by smurfy's website has set the left hand and arm actuator states to be enabled but the SHC-A omnipod doesn't have arm nor hand actuators, hence the error message. The second issue is that although the import detected the error it should have given you a loadout as closes to what you originally put in, which it doesn't. 

So:

@Smurfy
Can you please look over your export code so that it doesn't set the actuator state to true if the actuators are not togglable? 

And I will improve the import so that it gives you as much as it can. I will do this for 2.0 as I'm already deeply into the development phase of 2.0.

**Comment by smurfy** [comment]
has been fixed in todays release

**Comment by EmilyBjoerk** [comment]
I believe this has been ninja fixed in 2.0 already and I don't have a broken link to test with anymore so I will assume it is fixed until the issue resurfaces again. 

Thank you for taking the time to report this, it really helps me.
