### ISSUE TITLE
The weapon counter in the loadout window is incremented, but never decremented

### ISSUE THREAD

**Issue by VioletGiraffe** [EmilyBjoerk/lsml#528]
I'm talking about the Weapon column in the "Offensive Stats" group. I kept switching between SRM4 and SRM6, and now my SRM counter is up to 107. That Cat would be fun to drive, although it'd probably explode after the first volley :)

**Comment by EmilyBjoerk** [comment]
Hmm, so you keep adding and removing different sized launchers?

**Comment by VioletGiraffe** [comment]
Yep, and the counter keeps climbing! I didn't even notice it at first, but couldn't understand how come 5 tons of ammo equates to just 4 volleys. Then I realized what's going on.

**Comment by EmilyBjoerk** [comment]
Although I understand that this bug is annoying, you can work around it by opening and closing the mechlab window. 

Right now I feel like I would like to get this fix into Beta 4 but Beta 3 had some bad bugs and I really feel like it is prudent to get a fix out for those ASAP. So I will push this bug to Beta 5.

**Comment by VioletGiraffe** [comment]
Your project - your priorities :) In the meantime it's good to know the workaround, thank you!
