### ISSUE TITLE
Development preview 5 : Windows are oddly sized and cannot be moved

### ISSUE THREAD

**Issue by Question2** [EmilyBjoerk/lsml#541]
Part of the mech customization window is cut off and there is no way to move maximize or move the window.

![li song](https://cloud.githubusercontent.com/assets/1191378/14683158/9c50dd34-076c-11e6-983e-6b840aa452ce.jpg)

**Comment by EmilyBjoerk** [comment]
What screen resoultion is this?

**Comment by EmilyBjoerk** [comment]
I have looked into this a bit now, there is two issues: 

1. The window bar with the close and maximize buttons can end up outside of the screen for new windows. This is fixed by commit 62e7f44.
2. The minimum window size is too big, this can only be solved by implementing "compact mode" from 1.x. I was hoping to post-pone compact mode a bit but I might have to bump its priority.
