### ISSUE TITLE
cannot launch 1.9.9006_64bit in W10

### ISSUE THREAD

**Issue by partialist** [EmilyBjoerk/lsml#549]
LSML version: 1.9.9006_64bit.msi

A lsml:// link to any build that is related to the issue.
https://github.com/EmilyBjoerk/lsml/releases/download/1.9.9006/LSML_Setup-1.9.9006_64bit.msi

Steps to reproduce:
1. open lsml
2. loading window opens, then closes without launching the app

Actual result:
On first launch (as admin in Win10 Pro 64bit), the loading screen comes up with 'search for mwo install' text, but then just closes.
There is no gamedir location line in the settings.xml
When I add one, the same thing happens but with the text now being about 'reading cached game data'

Expected result:

Garage window should launch :3

**Comment by EmilyBjoerk** [comment]
Hello and thank you for reporting this issue.

On my windows 10 machine I am able to start lsml 64bit 1.9.9006. I need
more information to solve this. Could you please provide the following:

1. How many (if any) mwo installs do you have (normal/steam/PTS)?
2. Where are they installed?
3. Which Java version do you have? Does the problem persist if you use the
latest java version? (8u77 or newer)
4. Please attach the contents of the %appdata%/LiSoft/settings.xml file
5. Have you previously used lsml? If so, which was the last functioning
version?

Best regards,
Li

**Comment by partialist** [comment]
Hi!

1. Only one MWO install (Steam) - though I did previously have the standalone client installed (on a different drive)
2. the path is E:\Steam\SteamApps\Common\Mechwarrior Online
(old client was installed to O:\...)
3. Java is version 8 update 20 (build 1.8.0_20-b26)
4. xml file attached
(I had to zip as it wouldn't let me attach an xml file. Also I removed the line I had added.)
5. I have not previously used LSML
(I just discovered it recently - the path is O:\LSML\LSML)

[settings.zip](https://github.com/EmilyBjoerk/lsml/files/238263/settings.zip)

**Comment by EmilyBjoerk** [comment]
I will see if I can reproduce with that information later today. In the
meanwhile, could you please try updating your java version? I know that
there have been a few bug fixes in later versions that affects LSML.

I'm sorry that your first experience with LSML was such an annoyance.

Finally I just want to make sure that you know you're using a beta version
and that the last stable version is: 1.7.2
On 27 Apr 2016 10:47, "partialist" <notifications@github.com> wrote:

Hi!

   1. Only one MWO install (Steam) - though I did previously have the
   standalone client installed (on a different drive)
   2. the path is E:\Steam\SteamApps\Common\Mechwarrior Online (old client
   was installed to O:...)
   3. Java is version 8 update 20 (build 1.8.0_20-b26)
   4. xml file attached (I had to zip as it wouldn't let me attach an xml
   file. Also I removed the line I had added.)
   5. I have not previously used LSML (I just discovered it recently - the
   path is O:\LSML\LSML)

settings.zip <https://github.com/EmilyBjoerk/lsml/files/238263/settings.zip>

—
You are receiving this because you commented.

Reply to this email directly or view it on GitHub
<https://github.com/EmilyBjoerk/lsml/issues/549#issuecomment-215014389>

**Comment by partialist** [comment]
Oh no, please don't apologise! All good - I'm fully aware that I am trying to use something that's in development, and I would gladly help in any way possible.

Meanwhile, I updated Java and it LSML loaded properly!
I'm sorry I didn't think to try that before posting this issue... please go ahead and close this, and thanks for your time.

**Comment by EmilyBjoerk** [comment]
I'm glad that updating java solved the problem. It's also valuable for me
to know this if some one else has the same problem.

Please don't hesitate to open another issue if you find further problems
with the beta.
