### ISSUE TITLE
Sorting folders

### ISSUE THREAD

**Issue by Maqquan** [EmilyBjoerk/lsml#568]
There should be a way of sorting folders in between each other, not just putting them at the end of the list.

**Comment by EmilyBjoerk** [comment]
Folders are generally not sortable in any software. They are always sorted by name, date modified or type. Of those the only applicable attribute is name which the folders are already sorted by in LSML.

As such I feel that the issue is already resolved. If you feel that the current situation is unsatisfactory, please re-open the issue.
