### ISSUE TITLE
Incorrect heat capacity calculation and a major misconception in heat containment skill.

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#571]
Hi

I've found 2 issues with heat capacity calculation, one minor and one major.

**The Minor Issue:**
It looks like that the calculated heat capacity assumes that the internal engine heat sinks have the same heat capacity as the external ones.
For example, a mech with double heatsink upgrade and with an Inner-sphere XL250 engine with no skills and no extra double heat sinks should have 50 heat capacity (the engine has 10 dhs which add 20 heat cap on top of 30 base capacity)
However, in the current mechlab, the same mech have 46 capacity. The reason is that heat capacity of the internal engine double heat sinks are considered 1.5 (1.1 in clan case) which is incorrect. 

**The Major Issue**
It is revealed through testing that the heat containment skill only applies to the base 30 heat capacity, not the entire heat capacity of a mech.
For example, the heat containment skill should only increase the heat capacity of any mech by 3 (6 in case of double basics) regardless of the number of heatsinks the mech has.
Currently in Li-song mechlab, the heat containment skill applies to the overall heat capacity of a mech which is incorrect.

Thank you for the awesome job, and keep up the good work

**Comment by EmilyBjoerk** [comment]
I did some testing a while ago which confirmed 1.5 heat capacity of internal heat sinks. However I have done some more testing today which contradicts those results and supports 2.0 capacity for doubles for IS. I will need to repeat the tests for clan doubles and single heat sinks.

Also I will see if I can replicate the results from my previous tests that showed 1.5. 

The testing I did today also confirmed the heat containment skill only applies to the base heat, as opposed to the in-game description. I wonder if this is a bug in the game or if it is intentional. 

I will adjust the values as soon as I complete the rest of my testing. Thank you for your report.

**Comment by NavidA1** [comment]
**For IS here are the heat sink stats:**
Internal engine Single : 0.11 dissipation + 1.1 capacity
Engine slot Single and external single: 0.12 dissipation + 1.2 capacity
Internal engine Double: 0.2 dissipation + 2 capacity
Engine slot double and external double: 0.14 dissipation + 1.5 capacity

**For Clans:**
Internal engine Single : 0.11 dissipation + 1.1 capacity
Engine slot Single and external single: 0.12 dissipation + 1.2 capacity
Internal engine Double: 0.2 dissipation + 2 capacity
Engine slot double and external double: 0.15 dissipation + 1.1 capacity
