### ISSUE TITLE
Scrollbars are difficult to see

### ISSUE THREAD

**Issue by silvercheckmate** [EmilyBjoerk/lsml#592]
Scrollbars are difficult to see (light grey on dark grey) , a more contrasted colour scheme would be helpful!

**Comment by Zesaric** [comment]
I feel the same about the need for a more  contrasted color scheme.

Additionally, I suggest to color the "EMPTY" slots in white as opposed to the current dark grey. Grey always implies that this slot/option/dialogue is locked and that the user cannot do anything here. Even more so with the current dark grey, so the UI is misleading right now.

This is why I think re-coloring the "EMPTY" slots to pure white would be the best way to go here.

**Comment by Zesaric** [comment]
One additional thought here: As color always is a matter of taste it could be a good idea to add an option in the settings to select a color value for every UI element like

Empty slots
Dynamic Armor/Structure slots
Equipment slots
Background
Scrollbars
etc.

I am fully aware this requires much more work initially than to simply change the color of one element, but it could resolve any coloring issues in advance as every user can just use the colors they like best.

**Comment by EmilyBjoerk** [comment]
Please make a separate issue for each issue you have. I cannot plan my work
properly when each issue is actually multiple issues.

**Comment by Zesaric** [comment]
OK, sorry - will move my latest comment to a new issue and delete it here.

**Comment by EmilyBjoerk** [comment]
@silvercheckmate  could you please indicate what scrollbar is difficult to see and possibly provide a screenshot. I do not perceive a problem with any of the scrollbars I've checked. 

@Zesaric The "EMPTY" slots are coloured as such with the following rationale: Dark indicates that the slot is "recessed" so that it appears as a "slot" in which you can put something. The text is light on dark, as opposed to dark on light which implies that something is disabled. Admittedly I'm not happy with this myself but I haven't found a better solution yet. Photoshop suggestions are welcome in a new issue.

Due to time preassure I will not do this for 2.0.1 as originally planned.

**Comment by Zesaric** [comment]
Thanks for your explanations, I understand your rationale. As you say you are not 100% happy with the coloring yourself, I'll try to come up with an alternative theme using the CSS method you told me. I guess it will take some time to create a color theme that I am happy with - but as soon as I have it, I'll send the CSS files to you so you can opt to include them (or certain aspects) if you like the theme.
