### ISSUE TITLE
Equipment Group order reshuffle

### ISSUE THREAD

**Issue by silvercheckmate** [EmilyBjoerk/lsml#603]
I suggest changing the order of the last few equipment groups to 
- weapon modules
- mech modules
- consumables.

Weapon modules might not be swapped as often, but because they do affect the math and numbers of each build, it has the most consequence and should be higher up on the list.

**Comment by Zesaric** [comment]
This one is slightly related to #602 and #609, so I wanted to add a thought here.

I completely understand the reasoning that weapon modules affect the match most and I think a good point is made here by silvercheckmate.

However, following the concept of matching in-game sort orders as much as possible, I'd actually suggest to make the order Mech-Weapon-Hybrid-Consumable (i.e. identical to the game UI).

**Comment by EmilyBjoerk** [comment]
This is a difficult trade-off between being convenient and being consistent with in-game 'mechlab. 

One of the design goals with LSML is that it should be easy and quick to use and this speaks for breaking convention where it makes sense. On the other hand following convention also makes it easy to grasp and makes it easier to go between. 

Until I've made a decision on what is more important I will leave them as is.

**Comment by Zesaric** [comment]
As my job requires me to spend a lot of thought on end-user PC experience, I have often realized that it is a complete matter of taste whether a user feels something is convenient or not.

This is why I either try to give the end-user as much choice as possible (e.g. by providing customizable options) or try to adhere to standards.

Why?
If - metaphorically speaking - the standard is apples and I change it to oranges, the people who don't like oranges have a point in complaining that it isn't apples. If I stick with the standard of apples, the people who don't like apples accept it more easily, because it's the standard which I didn't change.

So what I'm trying to say is that sticking to the standards that MWO sets is the safer and thus probably the better route for aspects that are a matter of taste.

**Comment by EmilyBjoerk** [comment]
Agreed, convenience is a matter of taste. But I use objective measures such as number of clicks and scroll/move distance of mouse to guide my decisions. Regardless, it is still something I will need to spend some thought on.

**Comment by Zesaric** [comment]
Wow, I am impressed you're even including such data to guide your design decisions. That  even more shows the immense level of professionalism and dedication you put into LSML. I must say I truly admire your work, so keep it up - it's fabulous! :-)

As for the discussion between convenience and conventions: If somebody has a lot of work at hand, I always want to find ways to reduce the workload. That's why I suggested to just stick to standards for as many aspects as possible to keep discussion regarding these aspects short. So I really was writing all this not as a request but rather as an attempt to help you close this topic! :-)

**Comment by EmilyBjoerk** [comment]
This issue is superseded by #628.
