### ISSUE TITLE
Heat capacity has a -2 offset

### ISSUE THREAD

**Issue by NavidA1** [EmilyBjoerk/lsml#642]
Hi

I've noticed that the calculated heat capacity has a -2 offset

Version 2.0.4

example:
- Pick any mech (any type of heat sinks)
- strip it of all equipment (including engine)
- The base heat capacity is shown to be 28 without the heat containment skill, and 34, with the skill

The base heat value should be 30 before skill and 36 with the heat containment skill.
The -2 offset will be there even after you add additional heat sinks.
The heat cap data for all the heat sinks are correct. its just that -2 offset.

Thank you so much

**Comment by EmilyBjoerk** [comment]
First of, thank you for taking the time to report this. There have been errors in the past and having them reported is the only way of correcting them. 

Smokytehbear has done extensive research on heat values in MWO and published his findings here: https://steamcommunity.com/sharedfiles/filedetails/?id=686548357

I have been in contact with him and together we have done very through testing in private lobbies to validate all the heat results from his research. The -2 offset that you see is due to LSML assuming that you're moving at 100% throttle so it is using the formula in section 3.6 above with 100% throttle. 

Our test results are in this gdoc:
https://docs.google.com/spreadsheets/d/1Kj1QV97vB-hJgqsrKczG4yn7JNjKjG95DsBPzo-wbsU/edit#gid=1764568081 and they are consistent with the values computed by LSML at the time (with 100% throttle during the tests).

If you believe that LSML is calculating any of the heat or DPS values incorrectly, please construct a loadout that would disprove LSML's calculations and test it in a private lobby, record it and put the recording on a private youtube listing so that I can see what is happening and what the correct result should be.

Alternatively describe the test procedure in high detail to me and I may conduct it at some point in the future when I find time to. Fastest response if you do the testing though. 

If testing shows that LSML is indeed computing it wrong then I will happily fix it, but I need in-game measurements in a private lobby (or quick play)  to know what the real value should be.

Again thank you very much reporting the issue. I will leave this issue open for some time for comments and will close it in a few weeks if no comments are provided.

**Comment by NavidA1** [comment]
Thank you for the quick response.

I thought the heat capacity number in Li-Lab, is the base value.

Correct, wen moving full speed, around 2-3 heat will be added to your heat bar.
