### ISSUE TITLE
LSML / Huffman Table Changed?

### ISSUE THREAD

**Issue by smurfy** [EmilyBjoerk/lsml#707]
Hi,

With todays patch 1.4.130 it seems we reached the "end" of the pre-reserved range of huffman codes.
At least i'm getting an error :)
I tried verifing the problem with the latests Li Song Mechlab, but it does not like the patch-data (null pointer exception)

I disabled lsml link generation for now, if you have time please provide feedback / new huffman file. 
Then i need to remember how i converted it :)

**Comment by EmilyBjoerk** [comment]
Hi Philipp!

I'm moving tomorrow so all my stuff is in boxes... I'll see if I can setup
me laptop to check this out.

Sounds weird that we'd run out of the reserved range.

I'll take a look as soon as I can.

Den 15 aug. 2017 20:19 skrev "Philipp Andreas" <notifications@github.com>:

Hi,

With todays patch 1.4.130 it seems we reached the "end" of the pre-reserved
range of huffman codes.
At least i'm getting an error :)
I tried verifing the problem with the latests Li Song Mechlab, but it does
not like the patch-data (null pointer exception)

I disabled lsml link generation for now, if you have time please provide
feedback / new huffman file.
Then i need to remember how i converted it :)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EmilyBjoerk/lsml/issues/707>, or mute the thread

**Comment by EmilyBjoerk** [comment]
I'm on this now :)

Just FYI: With the introduction of the new armour types I'm removing support for old V1 format. I don't think anyone is using it.

**Comment by EmilyBjoerk** [comment]
@smurfy I remember that you generated item statistics for me before which I used for generating the Huffman tables. I can of course do without this but it would be helpful if you'd be able to do this again. 

I still have my old parsing code so I can reconstruct the format that you used. The first line contained the number of loadouts in total that were processed.  Then followed one line for each item with "<itemid> <count>" where count was the number of times it appeared in loadouts. The file was terminated by a single "q" on a new line.

If you're not able to do that, then that's fine. I'll just use the frequencies from the stock loadouts (which aren't as good but should still work somewhat).

**Comment by EmilyBjoerk** [comment]
Added the frequency data from the stock loadouts in the mean while in commit ece9612. 

The frequency table used is available here: https://gist.github.com/EmilyBjoerk/31f79d045772c874743049028ff01956.

The algorithm and data format for compression is the same. The only thing that has changed is the magic number at the start of the stream (incremented by one) and the frequency table used (see above).

**Comment by EmilyBjoerk** [comment]
@smurfy  what is the status on your side w.r.t. the new version?

**Comment by EmilyBjoerk** [comment]
@smurfy  ping?

**Comment by LiSongMWO** [comment]
Seems that smurfy is no longer maintained. Closing.
